/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#define STM32F103xB
#include <stm32f1xx.h>
#include <stm32f103xb.h>
//#include <system_stm32f1xx.h>
#include <stdint.h>

#define BV(n)     (1 << (n))
/**
 * @brief Add blocking delay
 *
 * @param ms number of milliseconds
 */
void ms_delay(int ms)
{
    while (ms-- > 0)
    {
        volatile int x = 500;
        while (x-- > 0)
            __asm("nop");
    }
}


void led_init(){
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
//	GPIOC->CRH |= 2 << GPIO_CRH_MODE13_Pos;
	GPIOC->CRH = 0x44244444;
}


void led_on(){
	GPIOC->BSRR = 1 << 13;
}

void led_off(){
	GPIOC->BRR = 1 << 13;
}


int main(void)
{
    /* Loop forever */
//	SystemInit();

	led_init();
	while(1){
		led_on();
		ms_delay(1000);
//		DelayMs(500);
		led_off();
		ms_delay(1000);
//		DelayMs(500);
	}


	for(;;);
}
